language: java

sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - secure: kE7B5JP1dPU7skPGBpoDwDd/5XjraM7MxMYrKnzaXLjXeUanU0e96FSpE+QeQ++OzRT702BSMQb3M5xSt8yB/PwZP7juFHwfcAX874+07FDECyguObLjBPWAfr0woipBnjCX6+55IgYaarrnQjAd24eRDPmCAeFIIXQlqUAYe0oskY2YClpCest08PFHZ8AryZcIorcVtDEOh5aNYAxoOZgsEPovncsRw7NhzJEx5u7UeOyokadpQB1WWq6ZynGRv0VCNXA3r5VqLauXxO/QeDtuef4nQ+9oj8RbHG+yRt6Vy7c6ttUhx6YH7jzzTsB8VNJ4VPlbuhL63iMDIUzEJxbG7QCgayYEwZiLS409G7dCdIG0RvuudBddo23cA+lXXDAi6HSrsgsMSgxw0pbP5Voi050nyeQYlkAKag9pyG2w4LSioDIZBbbXCc8lepaVLXP+EEVDHsSOIkapWkHvunOseAB8GCA7zhuQCUTrAW5P3wJIjbNAFvhBvUTBL0TpbNs+aKNXiCIMdxpJJULix391ppP7ZKrsqT4tmVWIQIfVVMqreKBmxfOozXxxpHP+jZHfoxZ67l8iMSjOpOqrqLujbOt6+sYu0nNX7XDynccCConKr6/VnX4fQwMPRszgA1Rf9Y7TFFZE8QEFGkDFxFuOD+B/KOVZLze1zaqwEMk=
    - secure: 3GErdFYODa0Cw9+DEJaYUT+ev5LzAVXRKlq4jUjhyC0XdcUgNwqH11d9oIgAwUDg5Ra2EnIBEZZIkPxzRegpHyo3Ys0ll5UvYyzyLU52ly+JkJU8oHRDbmCv0EYS6gMJkQNaDUhYq0XMmubTLCdnnvFq1PyrZDt4R3VTjKl615ykkZL4t9TRQFvRnMCq6qOLI9FqsdzuT8hHnXibtxBTDx1BT6Y2kehI2cAjAMsshLy19eNJpyx1li7RvuHR48uGE+Pltbiy8d1ejxx4J9jbpsNDDuyEgk6ajK3fxDq/H7aWDau+MfKnpieVFXb613u2UFCkbLFN0R3nFgl4ha2b6mO3k1pVPfwC12sRyk6KV7Xj3dgvAkfCuwZ7Oj7wEZPT4wuB6Uo9QT18blT6nIbqiqeYiCEZfUcDVRnj1knH48s75eHzdwvZxaZAqCijxsW8oO6iwqSxUWd1htXGmBkoNdLKm/ZqQFJScJ/Ur81Xn4nObfJkDofJXVuFzGrjR5ikKj+VX3FXxKvfBH9oCZbGIM798RLf2O5i1m6FSLUdmV0z91ehloP9L1kumpqkpqeLe7OPJK1km5crKK5CjgWUqHEhyyYn8jGiHbixfyYxw5o1dmSgYOCMgyOQrqvLHttkSooXiujlnaQyQtUXCpjW2qnEEqO1GAUR1JwIaKWS8UA=

addons:
  apt:
    packages:
      - python-yaml

before_script:
  - python etc/travis-sonatype.py

script: python etc/travis-build.py --settings ~/.m2/sonatype.xml
